version: "3"

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    networks:
      - simulador_default
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  simulador_default:
    name: simulador_default
    external: true
